sudo: false
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "pypy3"
install:
  - pip install -U tox
  - pip install -r requirements.txt
before_script:
  - cp play_template.wav play.wav
  - cp config/settings_template.json config/settings.json
  - cp config/server_template.json config/server.json
script: tox
