sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
install:
  - pip install -U tox
  - pip install -r requirements.txt
before_script:
  - cp play_template.wav play.wav
  - cp settings_template.json settings.json
  - cp server_template.json server.json
script: tox
